repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        args: [--count, --max-line-length=127, --exclude=venv]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
