#!/bin/sh -x
sudo kill $(cat lendbot.pid)
echo "exit code $?"
ls -l lendbot.pid
echo "exit code $?"
cat lendbot.pid
echo "exit code $?"
nohup venv/bin/python3 launcher.py &
echo "exit code $?"
echo "pid: $!"
sudo echo $! > lendbot.pid
echo "exit code $?"
